<footer class="footer">
  <div class="container">
    <div class="content has-text-centered">
      <p><strong>illaweb</strong> by <a href="https://www.illaweb.fr">Jean-marie</a>.
      </p>
      <p>tous droits de reproductions interdits sans autorisation d'illaweb.</p>
      <p>Travaux pour le P3 OpenClassroom</p>
    </div>
  </div>
  <div class="scrollup">
    <a href="#haut">
      <span class="icon">
        <i class="fas fa-caret-square-up fa-2x" title="Haut de page"></i>
      </span>
    </a>
  </div>
</footer>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script src="../Web/js/menu.js" type="text/javascript" charset="utf-8"></script>
<script src="../Webjs/smoothScroll.js" type="text/javascript" charset="utf-8"></script>
<script src="../Web/js/moderate.js" type="text/javascript" charset="utf-8"></script>
</body>
</html>
