<?php
use App\Check;

if ($_SESSION['authenticated']) {
    Check::verifSession();
}
?>
<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.0.0/js/all.js"></script>

  <link rel="stylesheet" href="<?= BASEPATH.'css/master.css'?>">
  <title><?= $title ?></title>
</head>
<body>
<header id="haut">
  <?php
  if (isset($_SESSION['authenticated'])) {
      include_once('navbar_admin.phtml');
  } else {
      include_once('navbar.phtml');
  }?>
</header>
