<nav class="navbar is-fixed-top is-warning" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <div class="navbar-item">
      <a class="navbar-item" href="<?= BASEPATH ?>" title="Retour à la page d'accueil">
          <img src="<?= BASEPATH.'/img/Logo.jpg'?>" alt="LoremFlickr image">
        <div class="brand-content">
          <div class="brand-title">
          <h1 class="title">
          Blog
          </h1>
          </div>
          <div class="brand-subtitle">
            <p>Mon livre</p>
          </div>
        </div>
      </a>
    </div>
    <button class="button navbar-burger" data-target="navMenu">
      <span></span>
      <span></span>
      <span></span>
    </button>
  </div>
  <div class="navbar-menu" id="navMenu">
  <div class="navbar-end">
    <a href="<?= BASEPATH ?>" class="navbar-item">Accueil</a>
    <a href="<?= BASEPATH.'Front/list'?>" class="navbar-item">Blog</a>
    <div class="navbar-item has-dropdown is-hoverable">
     <a class="navbar-link" href="">
      Admin
     </a>
     <div class="navbar-dropdown is-boxed">
       <a class="navbar-item" href="/documentation/overview/start/">
         Overview
       </a>
       <a class="navbar-item" href="https://bulma.io/documentation/modifiers/syntax/">
         Modifiers
       </a>
       <a class="navbar-item" href="https://bulma.io/documentation/columns/basics/">
         Columns
       </a>
       <a class="navbar-item" href="https://bulma.io/documentation/layout/container/">
         Layout
       </a>
       <a class="navbar-item" href="https://bulma.io/documentation/form/general/">
         Form
       </a>
       <hr class="navbar-divider">
       <a class="navbar-item" href="<?= BASEPATH.'Main/logout'?>">
        déconnection
       </a>

     </div>
  </div>
  </div>
</nav>
