<nav class="navbar is-fixed-top is-transparent" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <div class="navbar-item">
      <a class="navbar-item" href="<?= BASEPATH ?>" title="Retour à la page d'accueil">
          <img src="<?= BASEPATH.'/img/Logo.jpg'?>" alt="LoremFlickr image">
        <div class="brand-content">
          <div class="brand-title">
          <h1 class="title">
          Blog
          </h1>
          </div>
          <div class="brand-subtitle">
            <p>Mon livre</p>
          </div>
        </div>
      </a>
    </div>
    <button class="button navbar-burger" data-target="navMenu">
      <span></span>
      <span></span>
      <span></span>
    </button>
  </div>
  <div class="navbar-menu" id="navMenu">
  <div class="navbar-end">
    <a href="<?= BASEPATH ?>" class="navbar-item">Accueil</a>
    <a href="<?= BASEPATH.'Front/list'?>" class="navbar-item">Blog</a>
    <a href="<?= BASEPATH.'Main/login'?>" class="navbar-item">Admin</a>
  </div>
  </div>
</nav>
