<section class="section">
  <div class="container">
    <h1 class="title">Tableau de Bord</h1>
    <div class="columns">
      <div class="column">
        <div class="box notification is-link">
          <article class="media">
            <div class="media-left">
              <figure class="image is-64x64">
                <img src="<?= BASEPATH.'img/posts/Map_Alaska.png'?>" alt="">
              </figure>
            </div>
            <div class="media-content">
              <p class="subtitle is-3">
              Billets
              </p>
              <p><?= count($billets) ?> Billets publiés.</p>
            </div>
          </article>
        </div>
      </div>
      <div class="column">
        <div class="box notification is-info">
          <article class="media">
            <div class="media-left">
              <figure class="image is-64x64">
                <img src="<?= BASEPATH.'/img/Comments.png'?>" alt="">
              </figure>
            </div>
            <div class="media-content">
              <p class="subtitle is-3">
                Commentaires
              </p>
              <p><?= count($comments)?> commentaires publiés</p>
            </div>
          </article>
        </div>
      </div>
      <div class="column">
        <div class="box notification is-primary">
          <article class="media">
            <div class="media-left">
              <figure class="image is-64x64">
                <img src="<?= BASEPATH.'/img/Utilisateurs.png'?>" alt="">
              </figure>
            </div>
            <div class="media-content">
              <p class="subtitle is-3">
                Utilisateurs
              </p>
              <p>Nombres: <?= count($users) ?></p>
            </div>
          </article>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="section">
  <div class="container">
    <h2 class="title">Commentaires non lus</h2>
  </div>
</section>
