<div class="box">
  <div class="notification">
    <p class="title is-5">
      Modifier un utilisateur
      <form action="<?= BASEPATH.'Back/newUser'?>" method="post">
        <div class="field">
          <label for="username" class="label">Nom d'utilisateur</label>
          <input type="text" class="input" name="username" placeholder="Utilisateur"required>
        </div>
        <div class="field">
          <label for="email" class="label">Email</label>
          <input type="text" class="input" name="email" placeholder="votre adresse email" required>
        </div>
        <div class="field">
          <label for="password" class="label">Mot de Passe</label>
          <input type="password" class="input" name="password" placeholder="Mot de passe " required>
        </div>
        <div class="field">
          <div class="select">
            <select name="role">
              <option value="Administrateur">Administrateur</option>
              <option value="Modérateur">Modérateur</option>
            </select>
          </div>
        </div>
        <div class="field has-addons">
          <div class="control">
            <button class="button is-link" type="submit">Ajouté</button>
            <button class="button is-text" type="reset">Annulé</button>
          </div>
        </div>
      </form>
    </p>
  </div>
</div>
