<?php
/**
* @author    Jean-Marie HOLLAND <illaweb35@gmail.com>
*@copyright  (c) 2018, Jean-Marie HOLLAND. All Rights Reserved.
*
*@license    Lesser General Public Licence <http://www.gnu.org/copyleft/lesser.html>
*@link       https://illaweb.fr
*/

?>
<section class="section">
  <div class="container">
      <h1 class="title">Modifier un Billet</h1>
      <div class="content">
        <p>Utilisateur Connecté:
          <strong>
            <?= $_SESSION['name']?>
          </strong>
        </p>
      </div>
      <div class="box">
        <form action="<?= BASEPATH.'Backedit/Update/'.$billets->getId()?>" method="post" enctype="multipart/form-data">
          <div class="field">
            <label for="Titre" name="title" class="label" > Titre du billet</label>
            <input type="text" name="title" class="input" value="<?= htmlspecialchars($billets->getTitle())?>"/>
          </div>
          <div class="field">
            <div class="control">
              <textarea class="textarea" id="TinyModif" type="text" rows="6" name="content" ><?= $billets->getContent()?></textarea>
            </div>
          </div>
          <div class="columns">
            <div class="column">
              <div class="box">
                <p class="title is-5">Image à la une</p>
                <div class="columns">
                  <div class="column">
                    <div class="field">
                      <div class="file is-danger has-name is-boxed">
                        <label class="file-label">
                          <input class="file-input" type="file" name="image"/>
                          <span class="file-cta">
                            <span class="file-icon">
                              <i class="fas fa-cloud-upload-alt"></i>
                            </span>
                            <span class="file-label">
                              Modifier l'image
                            </span>
                          </span>
                          <span class="file-name">
                          Nom du fichier : _
                          <?php if (!isset($_POST['image'])) {
    echo $billets->getImage();
}?>
                          </span>
                        </label>
                        <div class="column">
                          <figure class="media-left">
                            <p class="image">
                              <img src="<?= BASEPATH.'img/posts/'.$billets->getImage()?>" alt="<?= $billets->getTitle()?>">
                            </p>
                          </figure>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="column">
              <div class="box">
                <div class="field">
                  <label class="label">Auteur</label>
                  <input type="text" name="author" class="input" value="Jean Forteroche"/>
                </div>
                <div class="field">
                  <label class="checkbox switch">
                    <input type="checkbox" name="posted" value="<?= $billets->getPosted()?>" <?php if ($billets->getPosted()== 1) {
    ?>checked="checked"<?php
}?>/>
                    <span class="slider round"></span>
                  </label>
                    Poster
                </div>
              </div>
            </div>
          </div>
          <div class="column">
           <div class="field is-grouped">
            <div class="control">
             <button type="submit" class="button is-link" title="Mettre à jour le Billet">Mise à jour</button>
            </div>
            <div class="control">
             <button class="button" title="Annulé et revenir au billet original">
              <a href="javascript:history.go(-1)">Annuler</a>
             </button>
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>
</section>
