<script src="https://cloud.tinymce.com/stable/tinymce.min.js"></script>
<script>tinymce.init({ selector:'textarea' });</script>
 <section class="section">
  <div class="container">
    <h1 class="title">Modifier un Billet</h1>
    <div class="content">
      <p>Utilisateur Connecté:
        <strong>
          <?= $_SESSION['name']?>
        </strong>
      </p>
    </div>
    <div class="box">
      <form action="<?= BASEPATH.'Backedit/Update'?>" method="post" enctype="multipart/form-data">
        <div class="field">
          <label for="Titre" name="title" class="label" > Titre du billet</label>
          <input type="text" name="title" class="input" placeholder="<?= htmlspecialchars($billets->getTitle())?>"/>
        </div>
        <div class="field">
          <div class="control">
            <textarea class="textarea" type="text"  rows="15" name="content" placeholder="<?= $billets->getContent()?>"></textarea>
          </div>
        </div>
        <div class="columns">
          <div class="column">
            <div class="box">
              <p class="title is-5">Image à la une</p>
                <div class="file">
                  <label class="file-label">
                    <label for="image" name="image" class="label">image (JPG,PNG,ou GIf | max: 2 mo)</label>
                    <input type="hidden" name="MAX_FILE_SIZE" value="<?= htmlspecialchars($billets->getImage())?>"/>
                    <input class="file-input" type="file" name="image">
                      <span class="file-cta">
                        <span class="file-icon">
                          <i class="fas fa-upload"></i>
                        </span>
                        <span class="file-label">
                          Choisir un fichier…
                        </span>
                      </span>
                  </label>
                </div>
              </div>
            </div>
            <div class="column">
              <div class="box">
                <div class="field">
                  <label class="label">Role</label>
                    <div class="control">
                      <div class="select">
                        <select name="author">
                          <option>Contributeur</option>
                          <option>Modérateur</option>
                        </select>
                      </div>
                    </div>
                  </div>
              <div class="field">
                <label class="checkbox switch">
                  <input type="checkbox" name="posted" value="<?= $billets->getPosted()?>" <?php if ($billets->getPosted()== 1) {
    ?>checked="checked"<?php
}?>/>
                  <span class="slider round"></span>
                </label>
                Poster
              </div>
                </div>
              </div>
            </div>
            <div class="column">
              <div class="field is-grouped">
                <div class="control">
                  <button type="submit" class="button is-link" title="Mettre à jour  le commentaire">Mise à jour</button>
                </div>
                <div class="control">
                  <button class="button"type="reset" title="effacer et recommencer la saisie">
                  Annuler
                  </button>
                </div>
            </div>
        </div>
      </form>
    </div>
  </div>
</section>
