<section class="section">
<h1>Connexion</h1>
  <div class="container">
    <div class="columns is-centered">
      <div class="box">
        <div class="column">
          <form action="<?= BASEPATH.'Back/login'?>" method="post">
            <div class="box">
              <figure class="image is-centered">
                  <img id="admin_img" src="<?= BASEPATH."/img/admin.png" ?>" alt="Administrateur avec casque et micro">
              </figure>
            </div>
            <div class="field">
              <label for="" class="label">
                Nom d'utilisateur
              </label>
              <input type="text" class="input" name="username" placeholder="utilisateur">
            </div>
            <div class="field">
              <label for="password" class="label">Password</label>
              <input type="password" class="input" name="password" placeholder="mot de passe">
            </div>
            <div class="field has-addons">
              <div class="control">
                <button class="button is-link" type="submit">Se connecter</button>
                <button class="button is-text" type="reset">Annulé</button>
                </div>
              </div>
              <p>Si vous ne possedez pas de compte vous pouvez vous
                <a href="<?= BASEPATH.'Main/signup/'?>">Inscrire</a>
                  <span class="icon has-text-info">
                    <i class="fas fa-user-plus"></i>
                  </span>
              </p>
            </div>
          </form>
        </div>
      </div>
    </div>
</section>
