<section class="section">
  <div class="content">
    <p>Utilisateur Connecté: <strong><?= $_SESSION['name']?></strong></p>
  </div>
  <?php foreach ($billets as $billet):?>
<div class="container">
    <div class="box">
      <article class="media">
        <figure class="media-left">
          <p class="image is-128x128">
            <img src="<?= BASEPATH.'img/posts/'.$billet->getImage() ?>" alt="<?= $billet->getTitle()?>">
          </p>
        </figure>
        <div class="media-content">
          <div class="content">
            <p>
              <a href="<?= BASEPATH .'Front/posting/'. $billet->getId()?>">
              <strong><?= htmlspecialchars($billet->getTitle()) ?></strong></a>
            </p>
            <br/>
            <p>
            <?=  substr(nl2br(htmlspecialchars($billet->getContent())), 0, 150); ?>...
            </p>
            <br/>
              <small>Publié le :
                <em>
                <?= date(' d m Y à H : i', strtotime($billet->getCreate_at())); ?>
              </em>
            </small>
            <p>Par <strong><?= htmlspecialchars($billet->getAuthor()) ?></strong>
            </p>
          </div>
          <nav class="level is-mobile">
        <div class="level-left">
          <a class="level-item" aria-label="mmodif" href="<?= BASEPATH.'Backedit/Update/'. $billet->getId()?>">
            <span class="icon is-small">
              <i class="fas fa-edit" aria-hidden="true"></i>
            </span>
          </a>
          <a class="level-item" aria-label="delete" href="<?= BASEPATH.'Backedit/delete/'. $billet->getId()?>">
            <span class="icon is-small">
              <i class="fas fa-trash" aria-hidden="true"></i>
            </span>
          </a>
        </div>
      </nav>
         </div>
      </article>
      </div>
    </div>
  <?php endforeach; ?>
</section>
