<section class="section">
  <div class="container">
    <h1>Liste des utilisateurs</h1>
    <table class="table">
      <thead>
        <tr>
          <th>Nom</th>
          <th>email</th>
          <th>Date de création</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th><?= htmlspecialchars($user->getName())?></th>
          <th><?= htmlspecialchars($user->getEmail())?></th>
          <th><?= htmlspecialchars($user->getdateCrea())?></th>
        </tr>
      </tbody>
    </table>
  </div>
</section>
