<script src="https://cloud.tinymce.com/stable/tinymce.min.js"></script>
<script>tinymce.init({ selector:'textarea' });</script>
 <section class="section">
  <div class="container">
<h1 class="title">Poster un Billet</h1>
<div class="box">
  <form action="<?= BASEPATH.'Back/write'?>" method="post" enctype="multipart/form-data">
    <div class="field">
      <label for="Titre" name="title" class="label" > Titre du billet</label>
      <input type="text" name="title" class="input" placeholder="Indiquer le titre de votre billet">
    </div>
    <div class="field">
      <div class="control">
        <textarea class="textarea" id="trumbowyg" type="text" name="content" placeholder="Votre contenu ici"></textarea>
      </div>
    </div>
    <div class="field">
      <label class ="label" for="image"> Insertion image du billet </label>
      <input type="file" class="input" name="image"/>
    </div>
    <div class="field is-grouped">
      <div class="control">
        <button type="submit" class="button" name="btn-comment" title="Enregistrer le commentaire">Enregistrer</button>
      </div>
      <div class="control">
        <button class="button"type="reset" title="effacer et recommencer la saisie">
          Effacer
        </button>
      </div>
    </div>
  </form>
</div>

  </div>
</section>
