<section class="hero is-fullheight">
<div class="hero-body">
  <div class="container has-text-centered">
    <h1 class="title" >
    Jean Forteroche
    </h1>
    <h2 class="subtitle ">
  Billet simple pour L'Alaska...
    </h2>
  <div class="container has-text-centered">
  <a href="#one">
    <span class="icon" id="circle" title="Vers les derniers billets">
      <i class="fas fa-arrow-circle-down fa-5x"></i>
    </span>
  </a>
  </div>
  </div>
</div>
</section>
<section  class="section is-medium " >
<div id="one"class="container has-text-centered">
Suivez mon nouveau roman...par épisode
</div>
</section>
<section class="section">
<div class="container">
  <div class="columns is-centered">
<?php if (empty($billets)):?>
  <p><strong>Il n'y a aucun billets publiés.</strong> _  Merci de revenir me visiter plus tard</p>
<?php else:?>
      <?php foreach ($billets as $billet):?>
    <div class="column is-3">
      <div class="card">
        <div class="card-image">
          <figure class="image ">
            <img id="homePost" src="<?= BASEPATH.'/img/posts/'. $billet->getImage()?>" alt="<?= $billet->getTitle()?>">
          </figure>
          <div class="card-content">
            <div class="media-content">
              <p class="title is-4" title="Lien vers le détail de l'billet">
                <a href="<?= BASEPATH.'Front/posting/'.$billet->getId()?>">
                <strong><?= htmlspecialchars($billet->getTitle()) ?></strong></a>
              </p>
              <p class="subtitle is-6">
                <strong><?=  htmlspecialchars($billet->getAuthor()) ?></strong>
              </p>
              <div class="content">
              <p><?= substr($billet->getContent(), 0, 150)?>...</p>
                 <time datetime="1-1-2016">
                   <small>Publié le : <em><?= date(' d m Y à H:i', strtotime($billet->getCreate_at())); ?></em></small>
                 </time>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <?php endforeach;?>
<?php endif?>
  </div>
</div>
</section>
