<?php
/**
* @author    Jean-Marie HOLLAND <illaweb35@gmail.com>
*@copyright  (c) 2018, Jean-Marie HOLLAND. All Rights Reserved.
*
*@license    Lesser General Public Licence <http://www.gnu.org/copyleft/lesser.html>
*@link       https://illaweb.fr
*/
?>
<section class="section">
  <?php foreach ($billets as $bil):?>
  <div class="container">
    <div class="box">
      <article class="media">
        <?php
        if (!empty($bil->getImage())) {
            ?>
        <figure class="media-left">
          <p class="image is-128x128">
            <img src="<?= BASEPATH.'img/posts/'.$bil->getImage()?>" alt="<?= $bil->getTitle()?>">
          </p>
        </figure>
      <?php
        }?>
        <div class="media-content">
          <div class="content">
            <p>
              <a href="<?= BASEPATH .'Front/posting/'. $bil->getId()?>">
              <strong><?= htmlspecialchars($bil->getTitle()) ?></strong></a>
            </p>
            <br/>
            <p>
            <?=  substr($bil->getContent(), 0, 150)?>...
            </p>
            <br/>
              <small>Publié le :
                <em>
                <?= date(' d - m - Y  à H : i', strtotime($bil->getCreate_at())); ?>
              </em>
            </small>
            <p>Par <strong><?= htmlspecialchars($bil->getAuthor()) ?></strong>
            </p>
          </div>
         </div>
      </article>
    </div>
  </div>
  <?php endforeach?>
</section>
