<section class="section">
  <div class="container">
   <img id="bandeau" src="<?= BASEPATH.'img/Welcome-2.jpg'?>" alt="image de bandeau header Journal et tasse de café">
  </div>
  <div id="top"class="container ">
    <article class="media">
      <div class="media-left">
        <figure class="image is-128x128">
          <img src="<?= BASEPATH.'img/posts/'.$billets->getImage()?>" alt="<?= htmlspecialchars($billets->getTitle())?>">
        </figure>
        </div>
        <div class="media-content">
          <div class="content">
            <p class="title is-4"><?= htmlspecialchars($billets->getTitle()) ?></p>
            <p><?= nl2br(htmlspecialchars($billets->getContent())) ?></p>
            <small>Publié le : <em><?= date(' d M Y à H:i', strtotime($billets->getCreate_at())); ?></em></small>
          </div>
        </div>
      </article>
      <hr/>
      <div class="columns">
        <div class="column">
          <article class="message is-info">
              <div class="message-header">
                <p><em><strong>Commentaires pour :  </strong></em><?= htmlspecialchars($billets->getTitle()) ?>
              </p>
              </div>
                <div class="message-body">
           <?php if (empty($comments)):?>
                <p class="bold">Il n'y a pas de commentaire pour cet article.
                </p>
                <hr/>
                <p class="has-text-centered">
                  Soyez le premier à ecrire un commentaire.
                </p>
              <?php else:?>
                <?php foreach ($comments as $comment):?>
                  <span class="underline">
                    <p>
                      <strong>
                        <?= htmlspecialchars($comment->getPseudo())?>
                      </strong> a écrit:
                    </p>
                  </span>
                    <small>Le <?= date('d M Y à H:i', strtotime($comment->getCreate_at()))?></small>

                    <p>
                      <?= nl2br(htmlspecialchars($comment->getContent())) ?>
                    </p>
                    <br/>
                    <p class="is-size-7">
                      <label class="checkbox" >
                        <input type="checkbox" name="moderate">
                        Signaler le commentaire
                      </label>
                    </p>
                  <hr/>
                <?php endforeach?>
              <?php endif ?>
                </div>
            </article>
          </div>
        <div class="column">
          <article class="media">
            <div class="media-content">
              <form action="<?= BASEPATH.'Front/addComment/'. $billets->getId()?>" method="post">
                <div class="field">
                  <div class="control">
                    <input class ="input" id="pseudo" name="pseudo" type="text" placeholder="Votre pseudo" required /><br />
                  </div>
                </div>
                <div class="field">
                  <div class="control">
                      <textarea class="textarea" id="content" name="content" placeholder="Votre commentaire" required></textarea><br />
                  </div>
                </div>
                <input class="input" type="hidden" name="bil_id" value="<?= $billets->getId() ?>" />
                  <div class="field is-grouped">
                    <div class="control">
                      <button type="submit" class="button" name="btn-comment" title="Enregistrer le commentaire">Commenter</button>
                    </div>
                    <div class="control">
                      <button class="button"type="reset" title="effacer et recommencer la saisie">
                        Effacer
                      </button>
                    </div>
                  </div>
                </form>
              </div>
            </article>
          </div>
        </div>
    </div>
  </section>
