<section class="section">
  <div class="container">
    <div class="card">
      <div class="card-image">
        <img src="../web/img/404.jpg" alt="Erreur 404">
      </div>
      <div class="card-content">
        <div class="notification is-danger">
           <strong><p><?= $errorMsg?>></p></strong>
        </div>
        <footer class="card-footer">
          <a href="javascript:history.go(-1)" class="button is-link"><span>Retour </span>
            <span class="icon">
            <i class="fas fa-undo"></i>
            </span>
          </a>
        </footer>
      </div>
    </div>
  </div>
</section>
