<?php
/**
* @author    Jean-Marie HOLLAND <illaweb35@gmail.com>
*@copyright  (c) 2018, Jean-Marie HOLLAND. All Rights Reserved.
*
*@license    Lesser General Public Licence <http://www.gnu.org/copyleft/lesser.html>
*@link       https://illaweb.fr
*/

 include_once('inc/header.phtml')?>
<section class="section">
  <div class="container">
    <?= $content ?>
  </div>
</section>
<?php include_once('inc/footer.phtml')?>
